---
# Never actually include your Rackspace username and API ey here -- they should
# be overwritten in an encrypted vault file.
rackspace_username: ''
rackspace_api_key: ''

# Default is to not backup, but this can be overwritten.
rackspace_backup: no
