---
- fail: msg="jupyterhub_admin_user is not defined"
  when: jupyterhub_admin_user == ''

- name: stop and remove cull container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: absent
    image: compmodels/cull
    name: cull

- name: create the /srv/cull directory
  file: path=/srv/cull state=directory

- name: copy the Dockerfile to /srv/cull
  template: src=Dockerfile.j2 dest=/srv/cull/Dockerfile

- name: build compmodels/cull image
  shell: docker build -t compmodels/cull /srv/cull

- name: get a jupyterhub api token
  command: docker exec jupyterhub jupyterhub token -f /srv/jupyterhub/jupyterhub_config.py {{ jupyterhub_admin_user }}
  register: jpy_api_token

- name: launch cull
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: running
    image: compmodels/cull
    detach: true
    name: cull
    net: host
    env:
      JPY_API_TOKEN: "{{ jpy_api_token.stdout }}"
