---
- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - common
  - rackspace
  - docker

- hosts: proxy
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - proxy

- hosts:
  - jupyterhub_nfs
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - nfs_server

- hosts: jupyterhub_nodes
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - nfs_client
  - node

- hosts: jupyterhub_host
  vars_files:
  - 'secrets.vault.yml'
  - 'users.vault.yml'
  - 'vars.yml'
  roles:
  - nfs_client
  - restuser
  - hub
