---
# Needed to make sure the API version matches with docker-py
docker_api_version: 1.16

# This is the name of an admin user of the JupyterHub instance, necessary
# to get an API key from JupyterHub
jupyterhub_admin_user: ''

# This is the directory you actually want to back up
backup_source_directory: ''

# This is the name of the CloudFiles container where the backups will be stored
backup_container: ''

# This is the GPG key id and password for the Duplicity backups. In general you
# should NEVER override this here -- override it in a vault file that is
# encrypted.
gpg_key: ''
gpg_pass: ''

# As with the GPG key, never actually include your Rackspace username and API
# key here -- they should be overwritten in an encrypted vault file.
rackspace_username: ''
rackspace_api_key: ''

# Root url of the hub
hub_base_url: ''

# User who will run nbgrader and root of the nbgrader directory structure
# relative to that user's home directory
nbgrader_user: ''
nbgrader_root: ''

# This is the auth token for JupyterHub. You can create it with:
#     openssl rand -hex 16
# Note that this should never be stored in plaintext; you should probably
# override it in an encrypted vault file.
configproxy_auth_token: ''

# This is the cookie secret for JupyterHub. You can create it with:
#     openssl rand -hex 2048
# Note that this should never be stored in plaintext; you should probably
# override it in an encrypted vault file.
cookie_secret: ''

# Get these from the Google OAuth application. Note that these should never
# be stored in plaintext, they should be overwritten in an encrypted vault file.
oauth_client_id: ''
oauth_client_secret: ''
oauth_callback_url: ''
oauth_hosted_domain: ''

# This is the path to where the docker TLS certificates are stored -- this is
# necessary for the SwarmSpawner to actually be able to communicate with swarm
docker_tls_path: /root/.docker

# These are the usernames that will have JupyterHub admin access. This list
# should probably be overwritten in an encrypted vault file.
jupyterhub_admins: []

# These are the usernames that have access to JupyterHub, but not admin access.
# This list should probably be overwritten in an encrypted vault file.
jupyterhub_users: []

# This is where the TLS certificates and keys should be stored for Docker
docker_tls_path: /root/.docker

# This is the port that swarm will attempt to connect to for each of the
# Docker hosts
docker_server_port: 2376

# This is the strategy that swarm will use to allocate containers. For details
# on the different options, see the swarm documentation.
docker_swarm_strategy: spread
