---
- fail: msg="configproxy_auth_token is not defined"
  when: configproxy_auth_token == ''
- fail: msg="cookie_secret is not defined"
  when: cookie_secret == ''
- fail: msg="oauth_client_id is not defined"
  when: oauth_client_id == ''
- fail: msg="oauth_client_secret is not defined"
  when: oauth_client_secret == ''
- fail: msg="oauth_callback_url is not defined"
  when: oauth_callback_url == ''
- fail: msg="oauth_hosted_domain is not defined"
  when: oauth_hosted_domain == ''
- fail: msg="admin list is empty"
  when: jupyterhub_admins|length == 0

- name: iptables configuration
  command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8000

- name: stop and remove jupyterhub container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: absent
    image: compmodels/jupyterhub
    name: jupyterhub

- name: create the jupyterhub_db directory
  file: path=/srv/jupyterhub_db state=directory

- name: create jupyterhub.sqlite
  file: path=/srv/jupyterhub_db/jupyterhub.sqlite state=touch mode=0600

- name: create the jupyterhub directory
  file: path=/srv/jupyterhub state=directory

- name: copy the Dockerfile to the jupyterhub directory
  copy:
    src: Dockerfile
    dest: /srv/jupyterhub/Dockerfile

- name: copy jupyterhub_config.py to the jupyterhub directory
  template:
    src: jupyterhub_config.py
    dest: /srv/jupyterhub/jupyterhub_config.py

- name: create the userlist
  template: src=userlist.j2 dest=/srv/jupyterhub/userlist

- name: add docker_oauth.py
  copy: src=docker_oauth.py dest=/srv/jupyterhub/docker_oauth.py

- name: add swarmspawner.py
  copy: src=swarmspawner.py dest=/srv/jupyterhub/swarmspawner.py

- name: build compmodels/jupyterhub image
  shell: docker build -t compmodels/jupyterhub /srv/jupyterhub

- name: launch jupyterhub
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: running
    image: compmodels/jupyterhub
    detach: true
    net: host
    name: jupyterhub
    env:
      OAUTH_CLIENT_ID: "{{ oauth_client_id }}"
      OAUTH_CLIENT_SECRET: "{{ oauth_client_secret }}"
      OAUTH_CALLBACK_URL: "{{ oauth_callback_url }}"
      HOSTED_DOMAIN: "{{ oauth_hosted_domain }}"
      JPY_COOKIE_SECRET: "{{ cookie_secret }}"
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
    volumes:
        - /var/run/docker.sock:/docker.sock
        - /var/run/restuser.sock:/restuser.sock
        - /srv/jupyterhub_db:/srv/jupyterhub_db
        - "{{ docker_tls_path }}:{{ docker_tls_path }}"
        - /home:/home
