---
- fail: msg="backup_source_directory is not defined"
  when: backup_source_directory == ''
- fail: msg="backup_container is not defined"
  when: backup_container == ''
- fail: msg="gpg_key is not defined"
  when: gpg_key == ''
- fail: msg="gpg_pass is not defined"
  when: gpg_pass == ''
- fail: msg="rackspace_username is not defined"
  when: rackspace_username == ''
- fail: msg="rackspace_api_key is not defined"
  when: rackspace_api_key == ''

- name: stop and remove backup container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: absent
    image: compmodels/backup
    name: backup

- name: launch backup
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: running
    image: compmodels/backup
    detach: true
    name: backup
    command: --gpg-key={{ gpg_key }} {{ backup_source_directory }} cf+http://{{ backup_container }}
    env:
      CLOUDFILES_USERNAME: "{{ rackspace_username }}"
      CLOUDFILES_APIKEY: "{{ rackspace_api_key }}"
      PASSPHRASE: "{{ gpg_pass }}"
    volumes:
      - /root/.gnupg:/root/.gnupg
      - /{{ backup_source_directory }}:/{{ backup_source_directory }}
