---
# These are the paths to the SSL certificate and key. This should be overwritten
# in an encrypted vault file.
ssl_cert_path: ''
ssl_key_path: ''

# These are the contents of the SSL certificate and key themselves. These should
# also be overwritten in an encrypted vault file.
ssl_cert: ''
ssl_key: ''

# This is the path to the static files for the singleuser notebook server
notebook_static_files: /srv/ipython/IPython/html/static/
