swarm:
    image: dockerswarm/swarm
    command: manage --strategy={{ docker_swarm_strategy }} --tlsverify --tlscacert={{ docker_tls_path }}/ca.pem --tlscert={{ docker_tls_path }}/cert.pem --tlskey={{ docker_tls_path }}/key.pem file:///root/.swarm/cluster
    volumes:
      - /root/.swarm:/root/.swarm
      - "{{ docker_tls_path }}:{{ docker_tls_path }}"
    ports:
      - "127.0.0.1:2375:2375"

jupyterhub:
    build: /srv/jupyterhub
    environment:
      OAUTH_CLIENT_ID: "{{ oauth_client_id }}"
      OAUTH_CLIENT_SECRET: "{{ oauth_client_secret }}"
      OAUTH_CALLBACK_URL: "{{ oauth_callback_url }}"
      HOSTED_DOMAIN: "{{ oauth_hosted_domain }}"
      JPY_COOKIE_SECRET: "{{ cookie_secret }}"
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
      DOCKER_TLS_CERT: "{{ docker_tls_path }}/cert.pem"
      DOCKER_TLS_KEY: "{{ docker_tls_path }}/key.pem"
      HUB_IP: "{{ servicenet_ip }}"
    volumes:
      - /srv/jupyterhub_db:/srv/jupyterhub_db
      - /srv/jupyterhub_users:/srv/jupyterhub_users
      - "{{ docker_tls_path }}:{{ docker_tls_path }}"
      - /var/run/restuser.sock:/restuser.sock
    ports:
      - "{{ servicenet_ip }}:8000:8000"
      - "{{ servicenet_ip }}:8081:8081"
    links:
      - swarm

backup:
    build: /srv/backup
    hostname: "{{ ansible_hostname }}"
    command: --gpg-key={{ gpg_key }} {{ backup_source_directory }} cf+http://{{ backup_container }}
    environment:
      CLOUDFILES_USERNAME: "{{ rackspace_username }}"
      CLOUDFILES_APIKEY: "{{ rackspace_api_key }}"
      PASSPHRASE: "{{ gpg_pass }}"
    volumes:
      - /root/.gnupg:/root/.gnupg
      - /srv/backup_cache:/root/.cache/duplicity
      - "{{ backup_source_directory }}:{{ backup_source_directory }}"

cull:
    build: /srv/cull
    command: --timeout=86400 --cull_every=3600 --url=http://jupyterhub:8081/hub
    environment:
      JPY_API_TOKEN:
    links:
      - jupyterhub

postgres:
    image: postgres
    environment:
      POSTGRES_DB: gradebook
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    ports:
      - "{{ ansible_ssh_host }}:5432:5432"

formgrader:
    build: /srv/formgrader
    environment:
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
      NOTEBOOK_URL_PREFIX: "{{ nbgrader_root }}"
      HUB_BASE_URL: "{{ hub_base_url }}"
      FORMGRADER_IP: "{{ servicenet_ip }}"
      ASSIGNMENTS_REPO_NAME: "{{ assignments_repo_name }}"
      ASSIGNMENTS_REPO_CLONE_URL: "{{ assignments_repo_clone_url }}"
      ASSIGNMENTS_REPO_URL: "{{ assignments_repo_url }} "
      NBGRADER_DB_URL: "postgresql://postgres:{{ postgres_password }}@{{ ansible_ssh_host }}:5432/gradebook"
      NBGRADER_USER: "{{ nbgrader_user }}"
      NBGRADER_USER_ID:
      JPY_API_TOKEN:
    volumes:
      - /home/{{ nbgrader_user }}:/home/{{ nbgrader_user }}
    links:
      - jupyterhub
      - postgres
    ports:
      - "{{ servicenet_ip }}:9000:9000"

stats:
    build: /srv/stats
    command: --file=/srv/stats_db/activity.sqlite --hub=http://jupyterhub:8081
    environment:
      JPY_API_TOKEN:
    volumes:
      - /srv/stats_db:/srv/stats_db
    links:
      - jupyterhub
