---
- fail: msg="course_id is not defined"
  when: course_id == ''

- name: stop running singleuser containers
  shell: docker stop $(docker ps -aq) || true
  sudo: yes

- name: remove singleuser containers
  shell: docker rm $(docker ps -aq) || true
  sudo: yes

- name: remove compmodels/systemuser images
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: absent
    image: compmodels/systemuser

- name: create the systemuser directory
  file: path=/srv/systemuser state=directory

- name: copy the Dockerfile to the systemuser directory
  copy:
    src: Dockerfile
    dest: /srv/systemuser/Dockerfile

- name: copy nbgrader_config to the systemuser directory
  template:
    src: nbgrader_config.py
    dest: /srv/systemuser/nbgrader_config.py
  sudo: yes
  tags:
    - docker-rebuild

- name: build compmodels/systemuser image
  shell: docker build -t compmodels/systemuser /srv/systemuser
