---
- fail: msg="jupyterhub_admin_user is not defined"
  when: jupyterhub_admin_user == ''

- name: stop and remove stats container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: absent
    image: compmodels/stats
    name: stats

- name: create the /srv/stats_db directory
  file: path=/srv/stats_db state=directory

- name: get a jupyterhub api token
  command: docker exec jupyterhub jupyterhub token -f /srv/jupyterhub/jupyterhub_config.py {{ jupyterhub_admin_user }}
  register: jpy_api_token

- name: launch stats
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: running
    image: compmodels/stats
    detach: true
    name: stats
    net: host
    command: --file=/srv/stats_db/activity.sqlite --hub=http://{{ servicenet_ip }}:8081
    env:
      JPY_API_TOKEN: "{{ jpy_api_token.stdout }}"
    volumes:
        - /srv/stats_db:/srv/stats_db
