---
- fail: msg="nfsserver is not defined"
  when: nfsserver == ''
- fail: msg="nfsdomain is not defined"
  when: nfsdomain == ''

- name: install nfs client
  apt: update_cache=yes cache_valid_time=600 name=nfs-common state=present

- name: unmount home
  shell: umount /home || true

- name: unmount exchange
  shell: umount {{ exchange }} || true

- name: mount home
  mount: name=/home src={{ hostvars[nfsserver]['servicenet_ip'] }}:/home fstype=nfs opts={{ nfsoptions }} state=mounted

- name: mount exchange
  mount: name={{ exchange }} src={{ hostvars[nfsserver]['servicenet_ip'] }}:/exchange fstype=nfs opts={{ nfsoptions }} state=mounted
