---
- fail: msg="nfsserver is not defined"
  when: nfsserver == ''
- fail: msg="nfsdomain is not defined"
  when: nfsdomain == ''

- name: install nfs client
  apt: update_cache=yes cache_valid_time=600 name=nfs-common state=present

- name: unmount home
  shell: umount /home || true

- name: unmount nbgrader
  shell: umount /srv/nbgrader || true

- name: mount home
  mount: name=/home src={{ hostvars[nfsserver]['ansible_ssh_host'] }}:/home fstype=nfs opts={{ nfsoptions }} state=mounted

- name: mount nbgrader
  mount: name=/srv/nbgrader src={{ hostvars[nfsserver]['ansible_ssh_host'] }}:/nbgrader fstype=nfs opts={{ nfsoptions }} state=mounted

- name: tweak idmapd settings
  lineinfile:
    dest: /etc/idmapd.conf
    regexp: '(# )?Domain =.*'
    line: 'Domain = {{ nfsdomain }}'

- name: restart idmapd
  service: name=idmapd state=restarted
